name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -tags=windows -ldflags -H=windowsgui -o loa.exe ./cmd/loa/

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        automatic_release_tag: latest
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: loa.exe
